version: '2'
services:
    startedkitapp-app:
        image: startedkitapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://startedkitapp-mysql:3306/startedkitapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=startedkitapp-elasticsearch:9300
        ports:
            - 7070:7070
    startedkitapp-mysql:
        extends:
            file: mysql.yml
            service: startedkitapp-mysql
    startedkitapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: startedkitapp-elasticsearch
